### ISSUE TITLE
Tag fora do body

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#1]
Tags nunca podem ficar fora da tag "body"
Informar na "head" somente metatags e importação de arquivos.

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L5

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina2.html#L5

**Comment by victor-padovam** [comment]
Corrigido.
