### ISSUE TITLE
Informar o título das páginas

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#10]
O título da página foi informado antes da "body".

É importante usarmos um título que descreva melhor do que se trata a nossa tabela de registros ao invés de "Tabela de Registros".  

No lugar de "Inclusão de Registros", também é melhor descrevermos qual é o registro que vamos incluir. ("Inclusão de Celular", por exemplo)

Utilizar os padrões de títulos disponíveis no bootstrap.

Consultar: https://getbootstrap.com/docs/3.3/getting-started/#examples

**Comment by victor-padovam** [comment]
Corrigido.
