### ISSUE TITLE
Optar por usar o layout de formulários horizontais

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#14]
Optar por usar o layout de formulários horizontais ao invés de tabelas. Pois tabelas são menos responsivas do que os formulários horizontais:

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina2.html#L17

Verifique a documentação em: https://getbootstrap.com/docs/3.3/css/#forms

**Comment by victor-padovam** [comment]
Corrigido.
