### ISSUE TITLE
Evitar usar css próprio

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#16]
A ideia do exercício é tirarmos o máximo do bootstrap, então devemos evitar usar css próprio, uma vez que dispomos de todo css disponível no framework:

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina2.html#L9

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L10

**Comment by victor-padovam** [comment]
Corrigido.
