### ISSUE TITLE
Melhorar nomes dos arquivos

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#17]
Por uma questão de boas práticas, optar por nomes dos arquivos que descrevam melhor o que fazem. Exemplos:

"Pagina1.html" poderia ser "lista_celulares.html" ou "celulares.html"
"Pagina2.html" poderia ser "novo_celular.html" ou "cadastrar_celular.html"

**Comment by victor-padovam** [comment]
Corrigido.
