### ISSUE TITLE
Identação ruim esta dificultando leitura do código

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#18]
A legibilidade do código esta comprometida com muitas linhas em branco, identação ruim e quebras de linha, segue alguns exemplos:

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L12
https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L24
https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L29
https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L49
https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L57
https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L81

**Comment by victor-padovam** [comment]
Corrigido.
