### ISSUE TITLE
Faltou informar as metatags do layout base do bootstrap

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#3]
Faltou informar na "head" as metatags do layout base do bootstrap.

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L3

Conforme a documentação:

https://getbootstrap.com/docs/3.3/getting-started/#template

**Comment by victor-padovam** [comment]
Corrigido.
