### ISSUE TITLE
Tag sobrando

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#4]
Essa tag "div" parece estar sem função clara.

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L30

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina2.html#L16

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina2.html#L35

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina2.html#L46

**Comment by victor-padovam** [comment]
Corrigido.
