### ISSUE TITLE
Incorreto uso do "col-*" em table

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#5]
Ai temos 2 erros:

1 - "div" do tipo "col-*" devem pertencer a uma div "row", e no código não existe uma "row".
2 - Outro erro é que o sistema de grid do bootstrap não permite usarmos em tables. (consultar a documentação: https://getbootstrap.com/docs/3.3/css/#tables e https://getbootstrap.com/docs/3.3/css/#grid

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L46

**Comment by victor-padovam** [comment]
Corrigido.
