### ISSUE TITLE
Usar ferramentas do framework bootstrap

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#7]
Aqui era pra dar preferencia as ferramentas do bootstrap, dispensando a necessidade de classes e no lugar das imagens, poderia ter utilizado botões com os ícones do framework.

Verificar em: https://getbootstrap.com/docs/3.3/components/#glyphicons

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L53

**Comment by victor-padovam** [comment]
Corrigido.
