### ISSUE TITLE
Navegação esta desconectada e sem padrão

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#8]
O controle de navegação esta desconectada do resto da página e também desalinhado.

Poderia ser usado os controles padrões do bootstrap, conforme documentação: https://getbootstrap.com/docs/3.3/components/#pagination

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L77

**Comment by victor-padovam** [comment]
Corrigido.
