### ISSUE TITLE
Botão de "Novo" não pode ficar junto a navegação de páginas

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/AelianTreinamento#9]
O botão "Novo" junto a navegação de páginas pode confundir o usuário.

O ideal é que ela fique acima da tabela, ou ao lado do título da página.

https://github.com/VictorPadovan1997/AelianTreinamento/blob/master/Pagina1.html#L82

**Comment by victor-padovam** [comment]
Corrigido.
